#https://www.docker.com/blog/docker-github-actions/
#https://stackoverflow.com/questions/60735334/github-continuous-integration-cmake-c
#https://dev.to/mihinduranasinghe/using-docker-containers-in-jobs-github-actions-3eof

name: BuildGoogleTest

on: 
  push:
#    tags:
#    - "v*.*.*"
    
  pull_request:
  
jobs:
  build-googletest:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TYPE: [Debug] #, Release]
        #container: ['debian:stretch']  
        
    env:
      BUILD_TYPE: ${{matrix.BUILD_TYPE}}
      BUILD_ROOT: /github/workspace
      BUILD_BIN_DIR: /github/workspace/build/${{matrix.BUILD_TYPE}} #can't do this at that level .... BUILD_BIN_DIR: $BUILD_ROOT/build/$BUILD_TYPE
      BUILD_ARTIFACT: DESKTOP_LINUX64@GTest@1.8.0.5dadbab@GNU_6.3.0 #D:\repo\DESKTOP_WIN64\GTest\1.8.0.5dadbab\MSVC_19.28.29336.0
       #container: ${{matrix.container}}  
        
    container:
      image: onbings/debian_stretch_builder:latest
      options: -v "/home/runner/work/googletest/googletest":"/github/workspace"
      credentials:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        
    steps:
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      shell: bash
      run: |
        echo BUILD_ROOT $BUILD_ROOT
        echo BUILD_BIN_DIR $BUILD_BIN_DIR
        echo BUILD_ARTIFACT $BUILD_ARTIFACT
        #cmake -E make_directory $BUILD_BIN_DIR
          # cmake -E make_directory ${{github.workspace}}/build/$BUILD_TYPE/install
    
    - name: Checkout googletest source
      uses: actions/checkout@v2 
        
    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
#Not with a container      working-directory: $BUILD_BIN_DIR    #${{github.workspace}}/build//${{env.BUILD_TYPE}}
      run: |
        cmake -E make_directory $BUILD_BIN_DIR
        #cmake -E make_directory $BUILD_BIN_DIR/install
        cd $BUILD_BIN_DIR
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$BUILD_BIN_DIR/install ../..
        
    - name: Build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        cd $BUILD_BIN_DIR
        cmake --build . --config $BUILD_TYPE

    - name: Test
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        cd $BUILD_BIN_DIR
        ctest -C $BUILD_TYPE
      
 #   - name: Debug Docker with a multiline script
 #     run: |
 #       pwd
 #       ls -al /github

        
    - name: Install
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        cd $BUILD_BIN_DIR
        cmake --build . --target install --config $BUILD_TYPE
        #cmake 3.15 cmake --install . --config $BUILD_TYPE --prefix $BUILD_BIN_DIR/install #${{env.BUILD_ROOT_DIR}}/build/install    

    - name: Upload Artifact on GitHub
      uses: actions/upload-artifact@v2
      with: 
          name: ${{env.BUILD_ARTIFACT}}
          path: ${{env.BUILD_BIN_DIR}}/install # /github/workspace/build/Debug/install #$BUILD_BIN_DIR/install
          if-no-files-found: error
          
    - name: Setup tmate session #https://github.com/mxschmitt/action-tmate
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      with:
        sudo: false          
